# Generated by Django 3.2.8 on 2021-11-17 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['id'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'ordering': ['id'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['id'], 'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.RemoveField(
            model_name='events',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='slug',
        ),
    ]
