# Generated by Django 3.2.8 on 2021-11-18 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gl', '0002_auto_20211117_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='groups',
            field=models.ManyToManyField(blank=True, to='gl.Groups', verbose_name='Группы'),
        ),
        migrations.RemoveField(
            model_name='events',
            name='person',
        ),
        migrations.AddField(
            model_name='events',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d/', verbose_name='Аватар'),
        ),
    ]
